import React from 'react';
import moment from 'moment';
import { connect } from 'react-redux';

import css from './PuzzleHeader.scss';

function TitleDiv({ title, date }) {
  return (title === "The Daily Mini" || title === "The Daily Maxi") ? (
    <div className={css.title}>
      {title}
      <span className={css.date}>
        {date.format('dddd') + ' ' + date.format('LL')}
      </span>
    </div>
  ) : (
    <div className={css.title}>
      Free Mode
    </div>
  );
}

class PuzzleHeader extends React.Component {
  render() {
    const title = this.props.title;
    const date = moment().format('dddd') + ' ' + moment().format('LL');

    return (
      <div className={css.headerContainer}>
        <div>
          <div className={css.title}>
            <TitleDiv title={title} date={date} />
          </div>
          <div className={css.subtitle}>
            Autogenerated by Preston Fu and Jeffrey Hu
          </div>
        </div>
      </div>
    )
  }
}

const mapStateToProps = (state, ownProps) => {
  const { puzzleMeta } = state.puzzle[ownProps.puzzleName] || {};
  return {
    ...puzzleMeta
  }
};

const connectedHeader = connect(mapStateToProps)(PuzzleHeader);

export default connectedHeader;
